version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: rommiez-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: RoomieZ
      MYSQL_USER: rommiez
      MYSQL_PASSWORD: rommiezpass
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    container_name: rommiez-api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: rommiez
      DB_PASSWORD: rommiezpass
      DB_DATABASE: RoomieZ
      DB_PORT: 3306
    ports:
      - "3010:3010"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
